"""
Unsloth configuration builder.

Auto-generates optimized Unsloth FastModel training scripts.
"""

from pathlib import Path
from typing import Any

from jinja2 import Template
from loguru import logger

from ..core.schemas import ExportConfig

# Unsloth training script template (current API: Unsloth + TRL SFTConfig;
# keep unsloth/unsloth_zoo upgraded: pip install --upgrade unsloth unsloth_zoo)
UNSLOTH_TRAIN_TEMPLATE = Template('''"""
Auto-generated Unsloth SFT training script.
Generated by Distill-Align (Unsloth current API — TRL SFTConfig).
"""

import torch
from unsloth import FastLanguageModel, is_bfloat16_supported
from datasets import load_dataset
from trl import SFTTrainer, SFTConfig

# =============================================================================
# Configuration
# =============================================================================

# Model configuration
MODEL_NAME = {{ model_name | tojson }}
MAX_SEQ_LENGTH = {{ max_seq_length }}
DTYPE = torch.{{ dtype }}
LOAD_IN_4BIT = {{ load_in_4bit }}

# LoRA configuration
LORA_R = {{ lora_r }}
LORA_ALPHA = {{ lora_alpha }}
LORA_DROPOUT = {{ lora_dropout }}
TARGET_MODULES = {{ target_modules }}

# Training configuration
BATCH_SIZE = {{ batch_size }}
GRADIENT_ACCUMULATION_STEPS = {{ gradient_accumulation_steps }}
NUM_EPOCHS = {{ num_epochs }}
LEARNING_RATE = {{ learning_rate }}
WARMUP_STEPS = {{ warmup_steps }}
MAX_STEPS = {{ max_steps }}
OPTIMIZER = {{ optimizer | tojson }}
LR_SCHEDULER = {{ lr_scheduler | tojson }}

# Dataset configuration
DATASET_PATH = {{ dataset_path | tojson }}
TEXT_FIELD = {{ text_field | tojson }}

# Output configuration
OUTPUT_DIR = {{ output_dir | tojson }}

# =============================================================================
# Model Loading
# =============================================================================

print(f"Loading model: {MODEL_NAME}")

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=MODEL_NAME,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=DTYPE,
    load_in_4bit=LOAD_IN_4BIT,
)

print("Model loaded successfully")

# =============================================================================
# LoRA Configuration
# =============================================================================

print("Configuring LoRA adapters...")

model = FastLanguageModel.get_peft_model(
    model,
    r=LORA_R,
    lora_alpha=LORA_ALPHA,
    lora_dropout=LORA_DROPOUT,
    target_modules=TARGET_MODULES,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=3407,
)

print(f"LoRA configured: r={LORA_R}, alpha={LORA_ALPHA}")

# =============================================================================
# Dataset Loading
# =============================================================================

print(f"Loading dataset from: {DATASET_PATH}")

dataset = load_dataset("json", data_files=DATASET_PATH, split="train")
print(f"Dataset loaded: {len(dataset)} examples")

# =============================================================================
# Training
# =============================================================================

print("Starting training...")

training_args = SFTConfig(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
    num_train_epochs=NUM_EPOCHS,
    learning_rate=LEARNING_RATE,
    warmup_steps=WARMUP_STEPS,
    max_steps=MAX_STEPS,
    optim=OPTIMIZER,
    lr_scheduler_type=LR_SCHEDULER,
    logging_steps=10,
    save_steps=100,
    save_total_limit=3,
    fp16=not is_bfloat16_supported(),
    bf16=is_bfloat16_supported(),
    seed=3407,
)

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    dataset_text_field=TEXT_FIELD,
    max_seq_length=MAX_SEQ_LENGTH,
    args=training_args,
)

trainer.train()

# =============================================================================
# Save Model
# =============================================================================

print(f"Saving model to: {OUTPUT_DIR}")

model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training complete!")
''')


class UnslothConfigBuilder:
    """Generates optimized Unsloth training scripts."""

    # Default LoRA target modules for common architectures
    DEFAULT_TARGET_MODULES = {
        "llama": ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        "mistral": ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        "mixtral": ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        "qwen": ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        "deepseek": ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        "phi": ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        "gemma": ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        "gpt-oss": ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    }

    def __init__(self, config: ExportConfig | None = None):
        """
        Initialize the Unsloth config builder.

        Args:
            config: Optional export configuration.
        """
        self.config = config or ExportConfig()

    def generate_script(
        self,
        dataset_path: str,
        output_dir: str = "./model_output",
        **kwargs,
    ) -> Path:
        """
        Generate an Unsloth training script.

        Args:
            dataset_path: Path to the training dataset.
            output_dir: Directory for model output.
            **kwargs: Additional configuration overrides.

        Returns:
            Path to the generated script.
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        # Detect model architecture for target modules
        model_name = kwargs.get("model_name", self.config.unsloth_model)
        target_modules = self._get_target_modules(model_name)

        # Prepare template variables
        _torch_available = torch is not None
        _dtype = (
            "bfloat16"
            if (_torch_available and torch.cuda.is_available() and torch.cuda.is_bf16_supported())
            else "float16"
        )

        template_vars = {
            "model_name": model_name,
            "max_seq_length": kwargs.get("max_seq_length", self.config.unsloth_max_seq_length),
            "dtype": _dtype,
            "load_in_4bit": kwargs.get("load_in_4bit", True),
            "lora_r": kwargs.get("lora_r", self.config.unsloth_lora_rank),
            "lora_alpha": kwargs.get("lora_alpha", self.config.unsloth_lora_alpha),
            "lora_dropout": kwargs.get("lora_dropout", 0.0),
            "target_modules": target_modules,
            "batch_size": kwargs.get("batch_size", 2),
            "gradient_accumulation_steps": kwargs.get("gradient_accumulation_steps", 4),
            "num_epochs": kwargs.get("num_epochs", 3),
            "learning_rate": kwargs.get("learning_rate", 2e-4),
            "warmup_steps": kwargs.get("warmup_steps", 5),
            "max_steps": kwargs.get("max_steps", -1),
            "optimizer": kwargs.get("optimizer", "adamw_8bit"),
            "lr_scheduler": kwargs.get("lr_scheduler", "linear"),
            "dataset_path": dataset_path,
            "text_field": kwargs.get("text_field", "conversations"),
            "output_dir": output_dir,
        }

        # Render template
        script_content = UNSLOTH_TRAIN_TEMPLATE.render(**template_vars)

        # Write script
        script_path = output_path / "train.py"
        with open(script_path, "w", encoding="utf-8") as f:
            f.write(script_content)

        logger.info(f"Generated Unsloth training script: {script_path}")
        return script_path

    def _get_target_modules(self, model_name: str) -> list:
        """
        Get target modules for LoRA based on model architecture.

        Args:
            model_name: Model name or path.

        Returns:
            List of target module names.
        """
        model_name_lower = model_name.lower()

        for arch, modules in self.DEFAULT_TARGET_MODULES.items():
            if arch in model_name_lower:
                return modules

        # Default to LLaMA-style modules
        return self.DEFAULT_TARGET_MODULES["llama"]

    def generate_config(self, **kwargs) -> dict[str, Any]:
        """
        Generate configuration dictionary.

        Args:
            **kwargs: Configuration overrides.

        Returns:
            Configuration dictionary.
        """
        return {
            "model_name": kwargs.get("model_name", self.config.unsloth_model),
            "max_seq_length": kwargs.get("max_seq_length", self.config.unsloth_max_seq_length),
            "lora_r": kwargs.get("lora_r", self.config.unsloth_lora_rank),
            "lora_alpha": kwargs.get("lora_alpha", self.config.unsloth_lora_alpha),
            "load_in_4bit": kwargs.get("load_in_4bit", True),
            "batch_size": kwargs.get("batch_size", 2),
            "gradient_accumulation_steps": kwargs.get("gradient_accumulation_steps", 4),
            "num_epochs": kwargs.get("num_epochs", 3),
            "learning_rate": kwargs.get("learning_rate", 2e-4),
        }

    def generate_preference_script(
        self,
        dataset_path: str,
        output_dir: str = "./model",
        method: str = "dpo",
        **kwargs,
    ) -> Path:
        """Generate a DPO/ORPO/KTO preference-training script (Unsloth + TRL).

        Mirrors the official Unsloth pattern (``PatchDPOTrainer`` + ``*Config``
        classes, ``is_bfloat16_supported``, ``optim="adamw_8bit"``). Preference
        tuning needs a much lower LR than SFT — default ``5e-7``, 1 epoch.

        Args:
            dataset_path: Path to the preference JSON (dpo/orpo/kto rows).
            output_dir: Where to save the trained adapter.
            method: One of ``"dpo"``, ``"orpo"``, ``"kto"``.
            **kwargs: Overrides (model_name, learning_rate, beta, num_epochs,
                max_length, max_prompt_length...).
        """
        method = method.lower()
        specs = {
            "dpo": ("DPOTrainer", "DPOConfig", True),  # (trainer, config, uses_beta)
            "orpo": ("ORPOTrainer", "ORPOConfig", False),
            "kto": ("KTOTrainer", "KTOConfig", True),
        }
        if method not in specs:
            raise ValueError(f"Unknown preference method: {method}")
        trainer_cls, config_cls, uses_beta = specs[method]
        model_name = kwargs.get("model_name", self.config.unsloth_model)
        # Forward slashes: Windows backslashes would be unicode escapes
        # inside the generated scripts' regular string literals.
        dataset_path = dataset_path.replace("\\", "/")
        output_dir = output_dir.replace("\\", "/")
        lr = kwargs.get("learning_rate", 5e-7)  # preference tuning needs low LR
        beta = kwargs.get("beta", 0.1)
        epochs = kwargs.get("num_epochs", 1)
        max_length = kwargs.get("max_length", 1024)
        max_prompt_length = kwargs.get("max_prompt_length", 512)
        beta_arg = f"\n    beta = {beta}," if uses_beta else ""
        script = f'''"""Auto-generated {method.upper()} training script (Distill-Align + Unsloth + TRL).

Keep unsloth current: pip install --upgrade --no-cache-dir unsloth unsloth_zoo
Dataset: {dataset_path} ({"prompt/chosen/rejected triples" if method in ("dpo", "orpo") else "prompt/completion/label rows"})
Refs: https://unsloth.ai/docs/get-started/reinforcement-learning-rl-guide/preference-dpo-orpo-and-kto
"""
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"  # optional: pin GPU

from unsloth import FastLanguageModel, PatchDPOTrainer
from unsloth import is_bfloat16_supported
PatchDPOTrainer()
from datasets import load_dataset
from trl import {trainer_cls}, {config_cls}

MAX_SEQ_LENGTH = {kwargs.get("max_seq_length", self.config.unsloth_max_seq_length)}

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="{model_name}",
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,
    load_in_4bit=True,
)
model = FastLanguageModel.get_peft_model(
    model,
    r={kwargs.get("lora_r", self.config.unsloth_lora_rank)},
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                    "gate_proj", "up_proj", "down_proj"],
    lora_alpha={kwargs.get("lora_alpha", self.config.unsloth_lora_alpha)},
    lora_dropout=0,  # 0 is optimized
    bias="none",  # "none" is optimized
    use_gradient_checkpointing="unsloth",  # 30% less VRAM
    random_state=3407,
    max_seq_length=MAX_SEQ_LENGTH,
)

dataset = load_dataset("json", data_files="{dataset_path}")["train"]

trainer = {trainer_cls}(
    model=model,
    ref_model=None,{beta_arg}
    args={config_cls}(
        per_device_train_batch_size=4,
        gradient_accumulation_steps=8,
        warmup_ratio=0.1,
        num_train_epochs={epochs},
        learning_rate={lr},
        fp16=not is_bfloat16_supported(),
        bf16=is_bfloat16_supported(),
        logging_steps=1,
        optim="adamw_8bit",
        seed=42,
        output_dir="{output_dir}",
    ),
    train_dataset=dataset,
    tokenizer=tokenizer,
    max_length={max_length},
    max_prompt_length={max_prompt_length},
)
trainer.train()
model.save_pretrained("{output_dir}")
tokenizer.save_pretrained("{output_dir}")
'''
        output_path = Path(output_dir).parent / f"train_{method}.py"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(script, encoding="utf-8")
        logger.info(f"Generated {method.upper()} training script: {output_path}")
        return output_path

    def generate_grpo_script(
        self,
        dataset_path: str,
        output_dir: str = "./model",
        reward_fn: str = "verifiable_reward",
        **kwargs,
    ) -> Path:
        """Generate a GRPO starter script (Unsloth + TRL, vLLM rollouts).

        The ``reward_fn`` placeholder must be replaced with a verifiable
        checker (math answer-match, code unit tests, format match). Unsloth
        auto-tunes ``unsloth_grpo_mini_batch`` / ``unsloth_logit_chunk_multiplier``
        for 7x+ longer contexts (Qwen3-8B GRPO: 110K on H100; gpt-oss: 380K on B200).

        Args:
            dataset_path: Path to GRPO groups JSON (prompt/completions/rewards).
            output_dir: Where to save the trained adapter.
            reward_fn: Name of the reward function to generate.
            **kwargs: Overrides (model_name, learning_rate, num_generations,
                max_completion_length, loss_type...).
        """
        model_name = kwargs.get("model_name", self.config.unsloth_model)
        dataset_path = dataset_path.replace("\\", "/")
        output_dir = output_dir.replace("\\", "/")
        script = f'''"""Auto-generated GRPO starter (Distill-Align + Unsloth + TRL).

Keep unsloth current: pip install --upgrade --no-cache-dir unsloth unsloth_zoo
Dataset: {dataset_path} (prompt/completions groups from `distill-align export --format grpo`)
Refs: https://unsloth.ai/docs/get-started/reinforcement-learning-rl-guide/grpo-long-context
"""
from unsloth import FastLanguageModel
from unsloth import is_bfloat16_supported
from datasets import load_dataset
from trl import GRPOTrainer, GRPOConfig

MAX_SEQ_LENGTH = {kwargs.get("max_seq_length", self.config.unsloth_max_seq_length)}

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="{model_name}",
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,
    load_in_4bit=True,
)
model = FastLanguageModel.get_peft_model(
    model,
    r={kwargs.get("lora_r", self.config.unsloth_lora_rank)},
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                    "gate_proj", "up_proj", "down_proj"],
    lora_alpha={kwargs.get("lora_alpha", self.config.unsloth_lora_alpha)},
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=3407,
    max_seq_length=MAX_SEQ_LENGTH,
)

dataset = load_dataset("json", data_files="{dataset_path}")["train"]


def {reward_fn}(completions, **kwargs):
    """TODO: replace with a verifiable reward (answer match / unit tests).

    `completions` is the rollout group for one prompt. Return one float
    per completion. The stub below rewards non-empty, well-formed answers.
    """
    rewards = []
    for c in completions:
        text = c if isinstance(c, str) else str(c)
        rewards.append(min(1.0, len(text.strip()) / 1000.0))
    return rewards


args = GRPOConfig(
    output_dir="{output_dir}",
    learning_rate={kwargs.get("learning_rate", 5e-6)},
    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,
    num_generations={kwargs.get("num_generations", 4)},  # rollouts per prompt
    max_prompt_length={kwargs.get("max_prompt_length", 512)},
    max_completion_length={kwargs.get("max_completion_length", 1024)},
    loss_type="{kwargs.get("loss_type", "grpo")}",
    use_vllm=True,  # vLLM speeds up rollouts ~11x (falls back if unavailable)
    fp16=not is_bfloat16_supported(),
    bf16=is_bfloat16_supported(),
    logging_steps=1,
    seed=42,
    # Unsloth auto-tunes unsloth_grpo_mini_batch / unsloth_logit_chunk_multiplier
)
trainer = GRPOTrainer(
    model=model,
    processing_class=tokenizer,
    args=args,
    train_dataset=dataset,
    reward_funcs={reward_fn},
)
trainer.train()
model.save_pretrained("{output_dir}")
'''
        output_path = Path(output_dir).parent / "train_grpo.py"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(script, encoding="utf-8")
        logger.info(f"Generated GRPO training script: {output_path}")
        return output_path


# Import torch at module level for template rendering
try:
    import torch  # type: ignore[import-not-found]
except ImportError:
    torch = None
