"""Central model catalog (single source of truth).

Consolidates Sep-2026 model IDs, per-1M-token pricing, context windows, and
lifecycle status for every provider Distill-Align talks to. ``tokenizer.py``
builds ``MODEL_PRICING`` from this table and ``registry.py`` takes its
per-provider defaults from :data:`PROVIDER_DEFAULTS`, so prices and defaults
can no longer drift apart.

Pricing sources: OpenAI + Anthropic + Mistral official pricing pages and the
Gemini API changelog (``official``); gateway list prices and vendor blogs
where official pages lag (``indicative``); self-hosted weights (``free``).
Indicative rows are conservative estimates — override via config when you
need invoice-grade accounting.
"""

from __future__ import annotations

from typing import Literal, TypedDict

PricingSource = Literal["official", "indicative", "free"]
ModelStatus = Literal["current", "legacy", "local"]


class ModelInfo(TypedDict, total=False):
    provider: str
    input: float  # USD per 1M input tokens
    output: float  # USD per 1M output tokens
    context: str  # context window, e.g. "1M", "256K"
    status: ModelStatus
    source: PricingSource
    ollama_tag: str  # `ollama pull <tag>`
    hf_id: str  # Hugging Face repo for weights / training
    note: str


# ── Catalog ───────────────────────────────────────────────────────────────
# Key = canonical API model id. Gateway prefixes (openai/..., :free, @date)
# are stripped by Tokenizer._resolve_pricing before lookup.

MODEL_CATALOG: dict[str, ModelInfo] = {
    # ——— OpenAI (official, Sep 2026; Sol promo thru Nov 21 2026) ———
    "gpt-5.6-sol": {
        "provider": "openai",
        "input": 4.00,
        "output": 20.00,
        "context": "1M",
        "status": "current",
        "source": "official",
    },
    "gpt-5.6-terra": {
        "provider": "openai",
        "input": 2.00,
        "output": 12.00,
        "context": "1M",
        "status": "current",
        "source": "official",
    },
    "gpt-5.6-luna": {
        "provider": "openai",
        "input": 0.20,
        "output": 1.20,
        "context": "1M",
        "status": "current",
        "source": "official",
    },
    "gpt-5.5": {
        "provider": "openai",
        "input": 5.00,
        "output": 30.00,
        "context": "400K",
        "status": "current",
        "source": "official",
    },
    "gpt-5.4": {
        "provider": "openai",
        "input": 2.50,
        "output": 15.00,
        "context": "272K",
        "status": "current",
        "source": "official",
    },
    "gpt-5.4-mini": {
        "provider": "openai",
        "input": 0.75,
        "output": 4.50,
        "context": "272K",
        "status": "current",
        "source": "official",
    },
    "gpt-5.4-nano": {
        "provider": "openai",
        "input": 0.20,
        "output": 1.25,
        "context": "272K",
        "status": "current",
        "source": "official",
    },
    "gpt-5": {
        "provider": "openai",
        "input": 1.25,
        "output": 10.00,
        "context": "272K",
        "status": "current",
        "source": "official",
    },
    "gpt-5-mini": {
        "provider": "openai",
        "input": 0.25,
        "output": 2.00,
        "context": "272K",
        "status": "current",
        "source": "official",
    },
    "gpt-5-nano": {
        "provider": "openai",
        "input": 0.05,
        "output": 0.40,
        "context": "272K",
        "status": "current",
        "source": "official",
    },
    "gpt-5.1": {
        "provider": "openai",
        "input": 1.25,
        "output": 10.00,
        "context": "400K",
        "status": "current",
        "source": "official",
    },
    "gpt-5-codex": {
        "provider": "openai",
        "input": 1.25,
        "output": 10.00,
        "context": "400K",
        "status": "current",
        "source": "official",
    },
    "o3": {
        "provider": "openai",
        "input": 2.00,
        "output": 8.00,
        "context": "200K",
        "status": "current",
        "source": "official",
    },
    "o1": {
        "provider": "openai",
        "input": 15.00,
        "output": 60.00,
        "context": "200K",
        "status": "legacy",
        "source": "official",
    },
    "o3-mini": {
        "provider": "openai",
        "input": 1.10,
        "output": 4.40,
        "context": "200K",
        "status": "legacy",
        "source": "official",
    },
    "o4-mini": {
        "provider": "openai",
        "input": 1.10,
        "output": 4.40,
        "context": "200K",
        "status": "legacy",
        "source": "official",
    },
    "gpt-4o": {
        "provider": "openai",
        "input": 2.50,
        "output": 10.00,
        "context": "128K",
        "status": "legacy",
        "source": "official",
    },
    "gpt-4o-mini": {
        "provider": "openai",
        "input": 0.15,
        "output": 0.60,
        "context": "128K",
        "status": "legacy",
        "source": "official",
    },
    "gpt-4.1": {
        "provider": "openai",
        "input": 2.00,
        "output": 8.00,
        "context": "1M",
        "status": "legacy",
        "source": "official",
    },
    "gpt-4.1-mini": {
        "provider": "openai",
        "input": 0.40,
        "output": 1.60,
        "context": "1M",
        "status": "legacy",
        "source": "official",
    },
    "gpt-4.1-nano": {
        "provider": "openai",
        "input": 0.10,
        "output": 0.40,
        "context": "1M",
        "status": "legacy",
        "source": "official",
    },
    "gpt-oss:20b": {
        "provider": "openai",
        "input": 0.0,
        "output": 0.0,
        "context": "128K",
        "status": "local",
        "source": "free",
        "ollama_tag": "gpt-oss:20b",
        "hf_id": "openai/gpt-oss-20b",
        "note": "Open-weight MoE (21B/3.6B active); runs in 16GB; adjustable reasoning.",
    },
    "gpt-oss:120b": {
        "provider": "openai",
        "input": 0.0,
        "output": 0.0,
        "context": "128K",
        "status": "local",
        "source": "free",
        "ollama_tag": "gpt-oss:120b",
        "hf_id": "openai/gpt-oss-120b",
    },
    # ——— Anthropic (official, Sep 2026) ———
    "claude-fable-5": {
        "provider": "anthropic",
        "input": 10.00,
        "output": 50.00,
        "context": "1M",
        "status": "current",
        "source": "official",
        "note": "Top tier above Opus; most capable.",
    },
    "claude-opus-4-8": {
        "provider": "anthropic",
        "input": 5.00,
        "output": 25.00,
        "context": "1M",
        "status": "current",
        "source": "official",
        "note": "Top Opus tier; long-horizon agentic coding.",
    },
    "claude-opus-4-7": {
        "provider": "anthropic",
        "input": 5.00,
        "output": 25.00,
        "context": "1M",
        "status": "legacy",
        "source": "official",
    },
    "claude-sonnet-5": {
        "provider": "anthropic",
        "input": 2.00,
        "output": 10.00,
        "context": "1M",
        "status": "current",
        "source": "official",
        "note": "Production default since Jun 30 2026.",
    },
    "claude-sonnet-4-6": {
        "provider": "anthropic",
        "input": 3.00,
        "output": 15.00,
        "context": "1M",
        "status": "legacy",
        "source": "official",
    },
    "claude-sonnet-4": {
        "provider": "anthropic",
        "input": 3.00,
        "output": 15.00,
        "context": "1M",
        "status": "legacy",
        "source": "official",
    },
    "claude-sonnet-4-20250514": {
        "provider": "anthropic",
        "input": 3.00,
        "output": 15.00,
        "context": "200K",
        "status": "legacy",
        "source": "official",
    },
    "claude-haiku-4-5": {
        "provider": "anthropic",
        "input": 1.00,
        "output": 5.00,
        "context": "200K",
        "status": "current",
        "source": "official",
    },
    "claude-haiku-4-5-20251001": {
        "provider": "anthropic",
        "input": 1.00,
        "output": 5.00,
        "context": "200K",
        "status": "current",
        "source": "official",
    },
    "claude-3-5-sonnet": {
        "provider": "anthropic",
        "input": 3.00,
        "output": 15.00,
        "context": "200K",
        "status": "legacy",
        "source": "official",
    },
    "claude-3-5-haiku": {
        "provider": "anthropic",
        "input": 0.80,
        "output": 4.00,
        "context": "200K",
        "status": "legacy",
        "source": "official",
    },
    "claude-3-opus": {
        "provider": "anthropic",
        "input": 15.00,
        "output": 75.00,
        "context": "200K",
        "status": "legacy",
        "source": "official",
    },
    "claude-3-haiku": {
        "provider": "anthropic",
        "input": 0.25,
        "output": 1.25,
        "context": "200K",
        "status": "legacy",
        "source": "official",
    },
    # ——— Google Gemini (2.x official-legacy; 3.x indicative, Sep 2026) ———
    "gemini-3.8-flash": {
        "provider": "gemini",
        "input": 0.10,
        "output": 0.40,
        "context": "1M",
        "status": "current",
        "source": "indicative",
        "note": "Latest Flash (Sep 2 2026); agent-first.",
    },
    "gemini-3.6-flash": {
        "provider": "gemini",
        "input": 0.10,
        "output": 0.40,
        "context": "1M",
        "status": "current",
        "source": "indicative",
    },
    "gemini-3.5-flash": {
        "provider": "gemini",
        "input": 0.10,
        "output": 0.40,
        "context": "1M",
        "status": "current",
        "source": "indicative",
        "note": "GA default (gemini-flash-latest); rivals Pro on benchmarks.",
    },
    "gemini-3.5-flash-lite": {
        "provider": "gemini",
        "input": 0.075,
        "output": 0.30,
        "context": "1M",
        "status": "current",
        "source": "indicative",
        "note": "Subagent / high-volume automation tier.",
    },
    "gemini-3.1-pro": {
        "provider": "gemini",
        "input": 1.25,
        "output": 10.00,
        "context": "1M",
        "status": "current",
        "source": "indicative",
        "note": "Flagship Pro; reasoning ceiling.",
    },
    "gemini-3-pro": {
        "provider": "gemini",
        "input": 1.25,
        "output": 10.00,
        "context": "1M",
        "status": "current",
        "source": "indicative",
    },
    "gemini-3-flash": {
        "provider": "gemini",
        "input": 0.10,
        "output": 0.40,
        "context": "1M",
        "status": "current",
        "source": "indicative",
    },
    "gemini-2.5-pro": {
        "provider": "gemini",
        "input": 1.25,
        "output": 10.00,
        "context": "1M",
        "status": "legacy",
        "source": "official",
    },
    "gemini-2.5-flash": {
        "provider": "gemini",
        "input": 0.15,
        "output": 0.60,
        "context": "1M",
        "status": "legacy",
        "source": "official",
    },
    "gemini-2.0-flash": {
        "provider": "gemini",
        "input": 0.10,
        "output": 0.40,
        "context": "1M",
        "status": "legacy",
        "source": "official",
        "note": "Shut down Jun 1 2026 — migrate to gemini-3.5-flash.",
    },
    "gemini-2.0-flash-lite": {
        "provider": "gemini",
        "input": 0.075,
        "output": 0.30,
        "context": "1M",
        "status": "legacy",
        "source": "official",
    },
    # ——— Alibaba Qwen (gateway list prices, Apr–Sep 2026) ———
    "qwen3-max": {
        "provider": "qwen",
        "input": 0.36,
        "output": 1.43,
        "context": "256K",
        "status": "current",
        "source": "indicative",
        "note": "Commercial flagship; thinking mode via enable_thinking.",
    },
    "qwen3-coder-next": {
        "provider": "qwen",
        "input": 0.20,
        "output": 1.50,
        "context": "256K",
        "status": "current",
        "source": "indicative",
        "note": "Agentic coding specialist; near-Sonnet on SWE-Bench.",
    },
    "qwen3.8-max": {
        "provider": "qwen",
        "input": 0.55,
        "output": 3.50,
        "context": "1M",
        "status": "current",
        "source": "indicative",
        "note": "Coding + cowork flagship; 1M context.",
    },
    "qwen3.6-plus": {
        "provider": "qwen",
        "input": 0.50,
        "output": 3.00,
        "context": "1M",
        "status": "current",
        "source": "indicative",
    },
    "qwen3.5-plus": {
        "provider": "qwen",
        "input": 0.40,
        "output": 2.40,
        "context": "1M",
        "status": "current",
        "source": "indicative",
    },
    "qwen3.5-flash": {
        "provider": "qwen",
        "input": 0.10,
        "output": 0.40,
        "context": "1M",
        "status": "current",
        "source": "indicative",
    },
    "qwen3.5-27b": {
        "provider": "qwen",
        "input": 0.29,
        "output": 2.05,
        "context": "256K",
        "status": "current",
        "source": "indicative",
    },
    "qwen3.5-122b-a10b": {
        "provider": "qwen",
        "input": 0.29,
        "output": 2.29,
        "context": "256K",
        "status": "current",
        "source": "indicative",
    },
    "qwen3.5-397b-a17b": {
        "provider": "qwen",
        "input": 0.55,
        "output": 3.50,
        "context": "256K",
        "status": "current",
        "source": "indicative",
    },
    "qwen3": {
        "provider": "qwen",
        "input": 0.0,
        "output": 0.0,
        "context": "256K",
        "status": "local",
        "source": "free",
        "ollama_tag": "qwen3:30b",
        "hf_id": "Qwen/Qwen3-30B-A3B",
        "note": "Open-weight family 0.6B–235B (dense + MoE); Apache 2.0.",
    },
    "qwen3:30b": {
        "provider": "qwen",
        "input": 0.0,
        "output": 0.0,
        "context": "256K",
        "status": "local",
        "source": "free",
        "ollama_tag": "qwen3:30b",
        "hf_id": "Qwen/Qwen3-30B-A3B",
        "note": "Balanced all-rounder for consumer hardware.",
    },
    "qwen3-coder": {
        "provider": "qwen",
        "input": 0.0,
        "output": 0.0,
        "context": "256K",
        "status": "local",
        "source": "free",
        "ollama_tag": "qwen3-coder:30b",
        "hf_id": "Qwen/Qwen3-Coder-30B-A3B-Instruct",
    },
    "qwen3-coder:30b": {
        "provider": "qwen",
        "input": 0.0,
        "output": 0.0,
        "context": "256K",
        "status": "local",
        "source": "free",
        "ollama_tag": "qwen3-coder:30b",
        "hf_id": "Qwen/Qwen3-Coder-30B-A3B-Instruct",
    },
    "Qwen/Qwen3-8B": {
        "provider": "qwen",
        "input": 0.0,
        "output": 0.0,
        "context": "256K",
        "status": "local",
        "source": "free",
        "hf_id": "Qwen/Qwen3-8B",
        "note": "Unsloth SFT/GRPO default; 110K ctx GRPO on H100.",
    },
    "qwen2.5": {
        "provider": "qwen",
        "input": 0.0,
        "output": 0.0,
        "context": "128K",
        "status": "legacy",
        "source": "free",
    },
    # ——— Meta Llama (open weights; $0 self-hosted) ———
    "llama4:scout": {
        "provider": "ollama",
        "input": 0.0,
        "output": 0.0,
        "context": "10M",
        "status": "local",
        "source": "free",
        "ollama_tag": "llama4:scout",
        "hf_id": "meta-llama/Llama-4-Scout-17B-16E-Instruct",
        "note": "109B MoE / 17B active; 10M context; multimodal.",
    },
    "llama4:maverick": {
        "provider": "ollama",
        "input": 0.0,
        "output": 0.0,
        "context": "1M",
        "status": "local",
        "source": "free",
        "ollama_tag": "llama4:maverick",
        "hf_id": "meta-llama/Llama-4-Maverick-17B-128E-Instruct",
        "note": "400B MoE / 17B active; MMLU-Pro 80.5.",
    },
    "meta-llama/Llama-4-Scout-17B-16E-Instruct": {
        "provider": "vllm",
        "input": 0.0,
        "output": 0.0,
        "context": "10M",
        "status": "local",
        "source": "free",
        "hf_id": "meta-llama/Llama-4-Scout-17B-16E-Instruct",
    },
    "meta-llama/Llama-4-Maverick-17B-128E-Instruct": {
        "provider": "vllm",
        "input": 0.0,
        "output": 0.0,
        "context": "1M",
        "status": "local",
        "source": "free",
        "hf_id": "meta-llama/Llama-4-Maverick-17B-128E-Instruct",
    },
    "llama3.1": {
        "provider": "ollama",
        "input": 0.0,
        "output": 0.0,
        "context": "128K",
        "status": "legacy",
        "source": "free",
    },
    "llama3.2": {
        "provider": "ollama",
        "input": 0.0,
        "output": 0.0,
        "context": "128K",
        "status": "legacy",
        "source": "free",
    },
    "llama3.3": {
        "provider": "ollama",
        "input": 0.0,
        "output": 0.0,
        "context": "128K",
        "status": "legacy",
        "source": "free",
    },
    "meta-llama/Meta-Llama-3.1-8B-Instruct": {
        "provider": "vllm",
        "input": 0.0,
        "output": 0.0,
        "context": "128K",
        "status": "legacy",
        "source": "free",
    },
    # ——— DeepSeek (official API, MIT weights) ———
    "deepseek-v4-flash": {
        "provider": "deepseek",
        "input": 0.14,
        "output": 0.28,
        "context": "1M",
        "status": "current",
        "source": "official",
        "hf_id": "deepseek-ai/DeepSeek-V4-Flash-0731",
        "note": "284B MoE / 13B active; Terminal-Bench 82.7; MIT.",
    },
    "deepseek-v4-flash-vision": {
        "provider": "deepseek",
        "input": 0.15,
        "output": 0.29,
        "context": "1M",
        "status": "current",
        "source": "official",
        "note": "API-only experimental vision; weights expected.",
    },
    "deepseek-v4-pro": {
        "provider": "deepseek",
        "input": 0.50,
        "output": 2.00,
        "context": "1M",
        "status": "current",
        "source": "indicative",
        "note": "1.6T MoE / 49B active; rivals closed flagships.",
    },
    "deepseek-reasoner": {
        "provider": "deepseek",
        "input": 0.55,
        "output": 2.19,
        "context": "128K",
        "status": "current",
        "source": "indicative",
    },
    "deepseek-chat": {
        "provider": "deepseek",
        "input": 0.27,
        "output": 1.10,
        "context": "128K",
        "status": "current",
        "source": "indicative",
    },
    "deepseek-r1": {
        "provider": "deepseek",
        "input": 0.0,
        "output": 0.0,
        "context": "128K",
        "status": "local",
        "source": "free",
        "ollama_tag": "deepseek-r1",
        "note": "Run locally; API available as deepseek-reasoner.",
    },
    "deepseek-v3": {
        "provider": "deepseek",
        "input": 0.0,
        "output": 0.0,
        "context": "128K",
        "status": "local",
        "source": "free",
    },
    # ——— Mistral (official La Plateforme, Jun 2026) ———
    "mistral-large-latest": {
        "provider": "mistral",
        "input": 0.50,
        "output": 1.50,
        "context": "256K",
        "status": "current",
        "source": "official",
        "note": "Large 3 (41B active / 675B MoE); Apache 2.0.",
    },
    "mistral-medium-3.5": {
        "provider": "mistral",
        "input": 0.40,
        "output": 2.00,
        "context": "256K",
        "status": "current",
        "source": "indicative",
        "note": "Frontier-class agentic + coding.",
    },
    "mistral-small-latest": {
        "provider": "mistral",
        "input": 0.15,
        "output": 0.60,
        "context": "128K",
        "status": "current",
        "source": "official",
    },
    "codestral-latest": {
        "provider": "mistral",
        "input": 0.30,
        "output": 0.90,
        "context": "256K",
        "status": "current",
        "source": "indicative",
        "note": "Coding specialist.",
    },
    "ministral-3-14b": {
        "provider": "mistral",
        "input": 0.0,
        "output": 0.0,
        "context": "128K",
        "status": "local",
        "source": "free",
        "note": "Apache 2.0; text + vision.",
    },
    "ministral-3-8b": {
        "provider": "mistral",
        "input": 0.0,
        "output": 0.0,
        "context": "128K",
        "status": "local",
        "source": "free",
    },
    "mistral": {
        "provider": "mistral",
        "input": 0.0,
        "output": 0.0,
        "context": "128K",
        "status": "legacy",
        "source": "free",
    },
    # ——— Google Gemma (open weights) ———
    "gemma4": {
        "provider": "gemini",
        "input": 0.0,
        "output": 0.0,
        "context": "128K",
        "status": "local",
        "source": "free",
        "ollama_tag": "gemma4:e4b",
        "note": "E2B/E4B/E12B/E27B multimodal; tool calling.",
    },
    # ——— Cohere / OpenRouter (gateway passthrough; priced per route) ———
    "command-r-plus": {
        "provider": "cohere",
        "input": 2.50,
        "output": 10.00,
        "context": "128K",
        "status": "current",
        "source": "indicative",
    },
}

# Legacy → 2026 successor (used for deprecation warnings, never silent rewrites).
MODEL_ALIASES: dict[str, str] = {
    "gpt-4o": "gpt-5-mini",
    "gpt-4o-mini": "gpt-5-mini",
    "gpt-4.1": "gpt-5.6-terra",
    "claude-sonnet-4-20250514": "claude-sonnet-5",
    "claude-sonnet-4-6": "claude-sonnet-5",
    "claude-opus-4-7": "claude-opus-4-8",
    "gemini-2.0-flash": "gemini-3.5-flash",
    "gemini-2.5-flash": "gemini-3.5-flash",
    "llama3.2": "qwen3:30b",
    "llama3.1": "llama4:scout",
    "Meta-Llama-3.1-8B-Instruct": "meta-llama/Llama-4-Scout-17B-16E-Instruct",
    "meta-llama/Meta-Llama-3.1-8B-Instruct": "meta-llama/Llama-4-Scout-17B-16E-Instruct",
}

# Per-provider production defaults (registry + clients + TUI read these).
PROVIDER_DEFAULTS: dict[str, str] = {
    "openai": "gpt-5-mini",
    "anthropic": "claude-sonnet-5",
    "gemini": "gemini-3.5-flash",
    "azure": "gpt-5-mini",
    "ollama": "qwen3:30b",
    "vllm": "meta-llama/Llama-4-Scout-17B-16E-Instruct",
    "openrouter": "qwen/qwen3-30b-a3b",
    "litellm": "gpt-5-mini",
    "together": "meta-llama/Llama-4-Scout-17B-16E-Instruct",
    "groq": "llama-3.3-70b-versatile",
    "mistral": "mistral-large-latest",
    "deepseek": "deepseek-v4-flash",
    "cohere": "command-r-plus",
    "qwen": "qwen3-max",
}

# Default training student (Unsloth SFT/GRPO recipes + export builders).
DEFAULT_TRAINING_MODEL = "Qwen/Qwen3-8B"


def pricing_table() -> dict[str, dict[str, float]]:
    """Build the ``{model: {input, output}}`` pricing map from the catalog."""
    return {mid: {"input": info["input"], "output": info["output"]} for mid, info in MODEL_CATALOG.items()}


def current_models(provider: str | None = None) -> list[str]:
    """List non-legacy model ids, optionally filtered by provider."""
    return [
        mid
        for mid, info in MODEL_CATALOG.items()
        if info.get("status") == "current" and (provider is None or info.get("provider") == provider)
    ]


def resolve_alias(model: str) -> str:
    """Return the 2026 successor for a legacy id, or the id unchanged."""
    return MODEL_ALIASES.get(model, model)
