#!/usr/bin/env python3
"""
Core Pydantic schemas for the Distill-Align framework.

These models ensure data integrity across the ingestion, synthesis, and export stages.
"""

import hashlib
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator, model_validator

# =============================================================================
# Ingestion Schemas
# =============================================================================


class SourceMetadata(BaseModel):
    """Metadata to preserve macro-context for each chunk."""

    source_type: Literal["pdf", "markdown", "code", "text"] = "text"
    file_path: str
    file_name: str
    title: str | None = None
    author: str | None = None
    language: str | None = None

    # Code-specific fields
    repository_url: str | None = None
    module_path: str | None = None

    # Document-specific fields
    section_headers: list[str] = Field(default_factory=list)
    page_number: int | None = None
    line_start: int | None = None
    line_end: int | None = None
    custom_tags: dict[str, Any] = Field(default_factory=dict)


class DataChunk(BaseModel):
    """Represents a single unit of raw or processed data."""

    content: str
    metadata: SourceMetadata
    id: str = ""  # Computed in model_validator
    tokens: int | None = None  # Estimated token count
    embedding: list[float] | None = None  # Optional for semantic dedup

    @model_validator(mode="after")
    def _generate_id(self) -> "DataChunk":
        if not self.id:
            file_path = self.metadata.file_path if self.metadata else ""
            line_start = self.metadata.line_start if self.metadata and self.metadata.line_start else 0
            hash_input = f"{file_path}:{line_start}:{self.content}"
            self.id = hashlib.sha256(hash_input.encode()).hexdigest()[:16]
        return self

    @property
    def source_type(self) -> str:
        return self.metadata.source_type


# =============================================================================
# Synthesis Schemas
# =============================================================================


class SynthesizedTurn(BaseModel):
    """A single turn in a multi-turn conversation."""

    role: Literal["system", "user", "assistant", "tool"]
    content: str


class ConversationSchema(BaseModel):
    """A structured conversation generated by the Socratic Transformer."""

    id: str  # UUID or deterministic hash
    source_chunk_id: str
    turns: list[SynthesizedTurn]
    reasoning_trace: str | None = None  # Captured deep thinking
    confidence_score: float | None = Field(None, ge=0.0, le=1.0)
    judge_scores: dict[str, Any] | None = None  # LLM-as-judge evaluation scores

    def get_system_prompt(self) -> str | None:
        """Extract system prompt if present."""
        for turn in self.turns:
            if turn.role == "system":
                return turn.content
        return None

    def get_user_turns(self) -> list[SynthesizedTurn]:
        """Extract all user turns."""
        return [t for t in self.turns if t.role == "user"]

    def get_assistant_turns(self) -> list[SynthesizedTurn]:
        """Extract all assistant turns."""
        return [t for t in self.turns if t.role == "assistant"]


# =============================================================================
# Export Schemas
# =============================================================================


class ShareGPTMessage(BaseModel):
    """Standard ShareGPT format message."""

    from_: Literal["human", "gpt", "system", "tool"] = Field(..., alias="from")
    value: str

    model_config = {"populate_by_name": True}


class ShareGPTItem(BaseModel):
    """A single ShareGPT conversation item."""

    id: str
    conversations: list[ShareGPTMessage]


class AlpacaEntry(BaseModel):
    """Standard Alpaca format entry."""

    instruction: str
    input: str
    output: str
    system: str | None = None

    @field_validator("system", mode="before")
    @classmethod
    def _empty_system_to_none(cls, v: str | None) -> str | None:
        if v == "":
            return None
        return v


# =============================================================================
# Configuration Schemas
# =============================================================================


class IngestionConfig(BaseModel):
    """Configuration for the ingestion pipeline."""

    chunk_size: int = Field(default=1000, ge=1)
    chunk_overlap: int = Field(default=200, ge=0)
    respect_headers: bool = True  # For markdown/code
    max_chunk_tokens: int = Field(default=4000, ge=1)
    include_metadata: bool = True
    scan_pii: bool = False  # Enable PII/secret scanning during ingestion
    redact_pii: bool = True  # Redact findings when scan_pii is enabled
    # Phase 2: chunker selection + semantic options (additive, default = legacy)
    chunker: Literal["auto", "markdown", "code", "recursive", "semantic", "parent_child", "late"] = "auto"
    semantic_breakpoint: Literal["percentile", "gradient", "fixed"] = "percentile"
    semantic_threshold: float = Field(default=75.0, ge=0.0, le=100.0)
    parent_child_ratio: int = Field(default=4, ge=2, le=16)
    contextual_prefix: bool = False  # Prepend heading path to each chunk
    serialize_tables: Literal["markdown", "sentences", "both"] = "both"
    enable_embeddings: bool = False  # Populate DataChunk.embedding via EmbeddingsClient


class SynthesisConfig(BaseModel):
    """Configuration for the synthesis pipeline."""

    llm_provider: str = "openai"
    model_name: str = "gpt-5-mini"
    base_url: str | None = None
    api_key: str | None = None
    max_concurrency: int = Field(default=5, ge=1)
    max_rpm: int = Field(default=60, ge=1)
    retry_attempts: int = Field(default=5, ge=1)
    temperature: float = Field(default=0.7, ge=0.0, le=2.0)
    max_tokens: int | None = None  # Maximum tokens to generate per LLM call (None = server default)
    socratic_enabled: bool = True
    scaffold_enabled: bool = True
    enable_judge: bool = False  # LLM-as-judge evaluation of generated conversations
    judge_model: str | None = None  # Override model for judge (defaults to model_name)
    # Phase 3: conversation mode routing (default = legacy socratic path)
    conversation_mode: Literal[
        "default",
        "teach",
        "debug",
        "review",
        "qa",
        "explain",
        "evol_instruct",
        "rag_qa",
        "tool_call",
        "constitutional",
        "distill",
    ] = "default"


class ExportConfig(BaseModel):
    """Configuration for the export pipeline."""

    formats: list[
        Literal[
            "sharegpt",
            "alpaca",
            "chatml",
            "conversation",
            "hf_messages",
            "jsonl",
            "parquet",
            "preference",
            "dpo",
            "orpo",
            "kto",
            "grpo",
            "agent",
            "rag_qa",
        ]
    ] = Field(default=["sharegpt"])
    output_dir: str = "./output"
    generate_unsloth_script: bool = True
    unsloth_model: str = "Qwen/Qwen3-8B"
    unsloth_max_seq_length: int = 2048
    unsloth_lora_rank: int = 16
    unsloth_lora_alpha: int = 16


class AppConfig(BaseModel):
    """Top-level application configuration."""

    ingestion: IngestionConfig = Field(default_factory=IngestionConfig)
    synthesis: SynthesisConfig = Field(default_factory=SynthesisConfig)
    export: ExportConfig = Field(default_factory=ExportConfig)
    log_level: str = "INFO"
    cache_dir: str = ".cache"
