"""Unit tests for CLI commands using Typer's CliRunner."""

import json
import os

import pytest
from typer.testing import CliRunner

from distill_align.cli.main import app

runner = CliRunner()


class TestCLIVersion:
    """Tests for the version command."""

    def test_version_output(self):
        """version command returns version string."""
        result = runner.invoke(app, ["version"])
        assert result.exit_code == 0
        assert "distill-align" in result.stdout.lower()
        assert "v" in result.stdout


class TestCLIStatus:
    """Tests for the status command."""

    def test_status_output(self):
        """status command returns system info."""
        result = runner.invoke(app, ["status"])
        assert result.exit_code == 0
        assert "Python" in result.stdout
        assert "Status" in result.stdout or "System" in result.stdout

    def test_status_reports_other_provider_keys(self, monkeypatch):
        """status reports non-OpenAI provider keys instead of 'Not set'."""
        monkeypatch.setenv("ANTHROPIC_API_KEY", "sk-test")
        result = runner.invoke(app, ["status"])
        assert result.exit_code == 0
        assert "Anthropic" in result.stdout
        assert "Not set" not in result.stdout


class TestCLIHelp:
    """Tests for help output."""

    def test_main_help(self):
        """Main app shows help with no args."""
        result = runner.invoke(app, [])
        assert result.exit_code in (0, 2)
        assert "Usage" in result.stdout or "Commands" in result.stdout

    def test_ingest_help(self):
        """ingest --help shows ingest options."""
        result = runner.invoke(app, ["ingest", "--help"])
        assert result.exit_code == 0
        assert "SOURCE" in result.stdout or "source" in result.stdout

    def test_synthesize_help(self):
        """synthesize --help shows synthesis options."""
        result = runner.invoke(app, ["synthesize", "--help"])
        assert result.exit_code == 0
        assert "INPUT" in result.stdout or "input" in result.stdout

    def test_export_help(self):
        """export --help shows export options."""
        result = runner.invoke(app, ["export", "--help"])
        assert result.exit_code == 0
        assert "INPUT" in result.stdout or "input" in result.stdout

    def test_validate_help(self):
        """validate --help shows validation options."""
        result = runner.invoke(app, ["validate", "--help"])
        assert result.exit_code == 0
        assert "INPUT" in result.stdout or "input" in result.stdout


class TestCLIInit:
    """Tests for init command."""

    def test_init_run_creates_config(self, tmp_path):
        """init run creates a config file."""
        config_path = tmp_path / "test_config.yaml"
        result = runner.invoke(app, ["init", "run", "--path", str(config_path), "--name", "test-proj"])
        assert result.exit_code == 0
        assert config_path.exists()
        content = config_path.read_text()
        assert "test-proj" in content or "project" in content

    def test_init_without_subcommand_creates_config(self, tmp_path):
        """Plain `distill-align init` creates a config file (documented usage)."""
        config_path = tmp_path / "proj.yaml"
        result = runner.invoke(app, ["init", "--path", str(config_path), "--name", "my-proj"])
        assert result.exit_code == 0
        assert config_path.exists()

    def test_generated_config_is_parseable(self, tmp_path):
        """The config generated by init must be valid YAML."""
        from distill_align.core.config_file import load_config

        config_path = tmp_path / "proj.yaml"
        result = runner.invoke(app, ["init", "--path", str(config_path)])
        assert result.exit_code == 0

        config = load_config(config_path)  # raises on invalid YAML
        assert config.project.name == "my-dataset"


class TestCLIIngest:
    """Tests for ingest command."""

    def test_ingest_missing_file(self):
        """ingest with non-existent path shows error."""
        result = runner.invoke(app, ["ingest", "/nonexistent/path.md"])
        assert result.exit_code == 1
        assert "Error" in result.stdout or "exist" in result.stdout

    def test_ingest_markdown_file(self, tmp_path):
        """ingest works with a valid markdown file."""
        md_file = tmp_path / "test.md"
        md_file.write_text("# Hello\n\nWorld.", encoding="utf-8")
        output = tmp_path / "out.json"
        result = runner.invoke(
            app,
            [
                "ingest",
                str(md_file),
                "--output",
                str(output),
            ],
        )
        assert result.exit_code == 0
        assert output.exists()
        data = json.loads(output.read_text())
        assert len(data) > 0

    def test_ingest_empty_directory_errors(self, tmp_path):
        """ingest on a directory with no supported files fails loudly."""
        empty_dir = tmp_path / "empty"
        empty_dir.mkdir()
        output = tmp_path / "out.json"
        result = runner.invoke(app, ["ingest", str(empty_dir), "--output", str(output)])
        assert result.exit_code == 1
        assert "No chunks" in result.stdout
        assert not output.exists()


class TestCLIExport:
    """Tests for export command."""

    def test_export_missing_file(self):
        """export with non-existent path shows error."""
        result = runner.invoke(app, ["export", "/nonexistent/in.json"])
        assert result.exit_code == 1
        assert "Error" in result.stdout or "exist" in result.stdout

    def test_export_valid_conversations(self, tmp_path):
        """export works with valid conversations JSON."""
        from distill_align.core.schemas import ConversationSchema, SynthesizedTurn

        conv = ConversationSchema(
            id="test-cli-export-1",
            source_chunk_id="chunk-1",
            turns=[
                SynthesizedTurn(role="user", content="Hello"),
                SynthesizedTurn(role="assistant", content="Hi there!"),
            ],
        )
        input_file = tmp_path / "conversations.json"
        data = [conv.model_dump()]
        input_file.write_text(json.dumps(data, indent=2), encoding="utf-8")
        out_dir = tmp_path / "export"
        result = runner.invoke(
            app,
            [
                "export",
                str(input_file),
                "--output-dir",
                str(out_dir),
                "--format",
                "sharegpt",
                "--no-unsloth",
            ],
        )
        assert result.exit_code == 0
        assert out_dir.exists()
        files = list(out_dir.glob("*.json"))
        assert len(files) >= 1

    def test_export_preference_format(self, tmp_path):
        """export --format preference works end-to-end (documented in README)."""
        from distill_align.core.schemas import ConversationSchema, SynthesizedTurn

        conv = ConversationSchema(
            id="test-cli-export-pref",
            source_chunk_id="chunk-1",
            turns=[
                SynthesizedTurn(role="user", content="Hello"),
                SynthesizedTurn(role="assistant", content="Hi there!"),
            ],
        )
        input_file = tmp_path / "conversations.json"
        input_file.write_text(json.dumps([conv.model_dump()], indent=2), encoding="utf-8")
        out_dir = tmp_path / "pref"
        result = runner.invoke(
            app,
            [
                "export",
                str(input_file),
                "--output-dir",
                str(out_dir),
                "--format",
                "preference",
                "--no-unsloth",
            ],
        )
        assert result.exit_code == 0
        pref_file = out_dir / "dataset_preference.json"
        assert pref_file.exists()
        data = json.loads(pref_file.read_text())
        assert len(data) == 1
        assert "chosen" in data[0] and "rejected" in data[0]

    def test_export_unknown_format(self, tmp_path):
        """export rejects an unknown --format with a helpful message."""
        from distill_align.core.schemas import ConversationSchema, SynthesizedTurn

        conv = ConversationSchema(
            id="test-cli-export-unknown",
            source_chunk_id="chunk-1",
            turns=[SynthesizedTurn(role="user", content="Hello")],
        )
        input_file = tmp_path / "conversations.json"
        input_file.write_text(json.dumps([conv.model_dump()], indent=2), encoding="utf-8")
        out_dir = tmp_path / "unknown"
        result = runner.invoke(
            app,
            ["export", str(input_file), "--output-dir", str(out_dir), "--format", "bogus", "--no-unsloth"],
        )
        assert result.exit_code == 1
        assert "bogus" in result.stdout
        assert "sharegpt" in result.stdout or "alpaca" in result.stdout


class TestCLIValidate:
    """Tests for validate command."""

    def test_validate_missing_file(self):
        """validate with non-existent path shows error."""
        result = runner.invoke(app, ["validate", "/nonexistent/in.json"])
        assert result.exit_code == 1
        assert "Error" in result.stdout or "exist" in result.stdout

    def test_validate_valid_data(self, tmp_path):
        """validate works with valid conversations JSON."""
        from distill_align.core.schemas import ConversationSchema, SynthesizedTurn

        conv = ConversationSchema(
            id="test-validate-1",
            source_chunk_id="chunk-val",
            turns=[
                SynthesizedTurn(role="user", content="Test"),
                SynthesizedTurn(role="assistant", content="Response"),
            ],
        )
        input_file = tmp_path / "valid.json"
        input_file.write_text(
            json.dumps([conv.model_dump()], indent=2),
            encoding="utf-8",
        )
        result = runner.invoke(app, ["validate", str(input_file), "--no-dedupe"])
        assert result.exit_code == 0


class TestCLISynthesize:
    """Tests for synthesize command validation."""

    @staticmethod
    def _chunks_file(tmp_path):
        chunk_file = tmp_path / "chunks.json"
        chunk_file.write_text(
            json.dumps(
                [
                    {
                        "id": "c1",
                        "content": "hello world",
                        "metadata": {"file_path": "a.md", "file_name": "a.md"},
                        "source": "a.md",
                        "index": 0,
                    }
                ]
            ),
            encoding="utf-8",
        )
        return chunk_file

    def test_synthesize_invalid_mode(self, tmp_path):
        """synthesize rejects an unknown --mode with a helpful message."""
        result = runner.invoke(app, ["synthesize", str(self._chunks_file(tmp_path)), "--mode", "bogus"])
        assert result.exit_code == 1
        assert "Invalid mode" in result.stdout
        assert "teach" in result.stdout and "explain" in result.stdout

    def test_synthesize_non_array_input(self, tmp_path):
        """synthesize rejects a JSON object (not an array) with a clear error."""
        bad_file = tmp_path / "bad.json"
        bad_file.write_text(json.dumps({"foo": "bar"}), encoding="utf-8")
        result = runner.invoke(app, ["synthesize", str(bad_file)])
        assert result.exit_code == 1
        assert "JSON array" in result.stdout


class TestCLIJobs:
    """Tests for jobs commands."""

    def test_jobs_list(self):
        """jobs list runs without error."""
        result = runner.invoke(app, ["jobs", "list"])
        assert result.exit_code == 0

    def test_jobs_list_invalid_status(self):
        """jobs list rejects an invalid --status with a helpful message."""
        result = runner.invoke(app, ["jobs", "list", "--status", "bogus"])
        assert result.exit_code == 1
        assert "Invalid status" in result.stdout
        assert "completed" in result.stdout or "running" in result.stdout

    def test_jobs_resume_missing(self):
        """jobs resume with bogus ID shows error."""
        result = runner.invoke(app, ["jobs", "resume", "nonexistent-job-id"])
        assert result.exit_code in (0, 1)

    def test_jobs_help(self):
        """jobs --help shows subcommands."""
        result = runner.invoke(app, ["jobs", "--help"])
        assert result.exit_code == 0


class TestCLIConfig:
    """Tests for config commands."""

    def test_config_show(self):
        """config show runs without error."""
        result = runner.invoke(app, ["config", "show"])
        assert result.exit_code == 0

    def test_config_show_invalid_yaml(self, tmp_path, monkeypatch):
        """config show reports unparseable config files instead of crashing."""
        (tmp_path / "distill-align.yaml").write_text("invalid: [unclosed", encoding="utf-8")
        monkeypatch.chdir(tmp_path)
        result = runner.invoke(app, ["config", "show"])
        assert result.exit_code == 1
        assert "Failed to parse" in result.stdout

    def test_config_path(self):
        """config path runs without error."""
        result = runner.invoke(app, ["config", "path"])
        assert result.exit_code == 0


class TestCLIErrorCases:
    """Tests for CLI error handling."""

    def test_unknown_command(self):
        """Unknown command shows error."""
        result = runner.invoke(app, ["nonexistent-command-xyz"])
        assert result.exit_code != 0

    def test_config_flag_missing_file(self):
        """--config pointing at a missing file errors cleanly."""
        result = runner.invoke(app, ["--config", "/nonexistent/config.yaml", "version"])
        assert result.exit_code == 1
        assert "Config file not found" in result.stdout

    def test_ingest_without_source(self):
        """ingest without source shows usage."""
        result = runner.invoke(app, ["ingest"])
        assert result.exit_code != 0

    def test_synthesize_without_input(self):
        """synthesize without input shows usage."""
        result = runner.invoke(app, ["synthesize"])
        assert result.exit_code != 0

    def test_export_without_input(self):
        """export without input shows usage."""
        result = runner.invoke(app, ["export"])
        assert result.exit_code != 0

    def test_validate_without_input(self):
        """validate without input shows usage."""
        result = runner.invoke(app, ["validate"])
        assert result.exit_code != 0

    @pytest.mark.skipif(os.environ.get("CI") == "true", reason="TUI needs a TTY, not available in CI")
    def test_tui_launches(self):
        """tui command runs (may fail if no TTY)."""
        result = runner.invoke(app, ["tui"])
        # TUI may fail without a real TTY, but should not crash
        # CI env skips the TUI launch gracefully
        assert result.exit_code in (0, 1)
